// <auto-generated />
using AsyncInnManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsyncInnManagementSystem.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20230719220352_AddSeeding")]
    partial class AddSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AsyncInnManagementSystem.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "condition"
                        },
                        new
                        {
                            Id = 2,
                            Name = "coffee and tea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "big sofa"
                        });
                });

            modelBuilder.Entity("AsyncInnManagementSystem.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "AMMAN",
                            Name = "Marriot",
                            Phone = "01345775",
                            State = "west",
                            StreetAddress = "12.456",
                            country = "Jordan"
                        },
                        new
                        {
                            Id = 2,
                            City = "Aqaba",
                            Name = "chiraton",
                            Phone = "154634645",
                            State = "north",
                            StreetAddress = "100.123",
                            country = "Jordan"
                        },
                        new
                        {
                            Id = 3,
                            City = "Irbd",
                            Name = "Rotana",
                            Phone = "154545454",
                            State = "south",
                            StreetAddress = "120.456",
                            country = "Jordan"
                        });
                });

            modelBuilder.Entity("AsyncInnManagementSystem.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Layout = 1,
                            Name = "first Room"
                        },
                        new
                        {
                            Id = 2,
                            Layout = 3,
                            Name = "secound Room"
                        },
                        new
                        {
                            Id = 3,
                            Layout = 1,
                            Name = "third Room"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
